name: BTCM2020

on:
push:
branches: [main]

jobs:

build:

run-on: ubuntu-latest

steps:
- uses: actions/checkout@v2s

- name: Installing Node
  uses: actions/setup-node@v2-beta
with: 
  node-version 13

- name: Installing surge
  run: npm install --globall surge
- name: Deploy using surge
  run: surge ./ bctm2020.surge.sh --token $ {{ serets.Surge_Token }}
